"""Compare two geometric reCLAMM runs against matched arb-only baselines.

This script reuses the same AAVE/ETH reCLAMM fingerprint and parameter wiring as
``compare_reclamm_thermostats.py``, but runs only the geometric interpolation
mode and plots:
1. Share price / TVL over time in absolute USD terms
2. Pool weights over time
3. Estimated gross swap volume over time
4. Noise-model improvement over arb-only over time

Because these runs use no LP supply changes, share price and TVL are the same
series here.

Usage:
    python scripts/reclamm/compare_reclamm_geometric_noise_runs.py
    python scripts/reclamm/compare_reclamm_geometric_noise_runs.py \
        --adjacent-csv scripts/results/...csv --adjacent-row-index 0
"""

from __future__ import annotations

import argparse
import importlib.util
import json
from pathlib import Path
from typing import Mapping, Optional, Sequence

import numpy as np
import pandas as pd


DEFAULT_SOURCE_HEATMAP_DESCRIPTION = (
    "market_linear price_ratio_vs_margin heatmap with shift_exp fixed at 0.10"
)
DEFAULT_RUN_SPECS = [
    {
        "name": "Green cell near price_ratio 1.31",
        "price_ratio": 1.31,
        "centeredness_margin": 0.6763157894736842,
        "daily_price_shift_exponent": 0.10,
        "tvl_usd": 1_000_000.0,
        "color": "C0",
        "reason": (
            "Geometric noise-model run taken from the positive cell in the "
            "market_linear price_ratio-vs-margin heatmap at price_ratio=1.31 and the "
            "lower adjacent centeredness row."
        ),
    },
    {
        "name": "Red cell near price_ratio 1.31",
        "price_ratio": 1.31,
        "centeredness_margin": 0.7210526315789474,
        "daily_price_shift_exponent": 0.10,
        "tvl_usd": 1_000_000.0,
        "color": "C1",
        "reason": (
            "Geometric noise-model run taken from the negative cell directly "
            "above the green cell in the market_linear price_ratio-vs-margin heatmap "
            "at price_ratio=1.31."
        ),
    },
]
DEFAULT_OUTPUT_FILE = "reclamm_geometric_noise_pair_compare.png"
VARIANT_STYLES = {
    "noise": {"linestyle": "-", "alpha": 0.95, "linewidth": 2.2},
    "arb": {"linestyle": "--", "alpha": 0.85, "linewidth": 2.0},
}


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Compare two geometric reCLAMM runs plus matched arb-only baselines. "
            "Optionally source the run pair from an adjacent-heatmap CSV row."
        )
    )
    parser.add_argument(
        "--adjacent-csv",
        default=None,
        help="Optional adjacent-pairs CSV generated by find_adjacent_heatmap_pairs.py.",
    )
    parser.add_argument(
        "--adjacent-row-index",
        type=int,
        default=0,
        help="Which row from --adjacent-csv to use. Defaults to the largest-diff row.",
    )
    parser.add_argument(
        "--output-file",
        default=None,
        help="Optional PNG output path override.",
    )
    return parser.parse_args()


def load_runtime_dependencies():
    """Load heavy runtime dependencies only when an actual simulation is needed."""
    thermostat_path = Path(__file__).with_name("compare_reclamm_thermostats.py")
    spec = importlib.util.spec_from_file_location(
        "reclamm_compare_reclamm_thermostats_runtime",
        thermostat_path,
    )
    if spec is None or spec.loader is None:
        raise RuntimeError(f"Could not load compare module from {thermostat_path}")
    thermostat_compare = importlib.util.module_from_spec(spec)
    try:
        spec.loader.exec_module(thermostat_compare)
    except ModuleNotFoundError as exc:  # pragma: no cover - depends on local runtime deps
        if exc.name == "jax":
            raise RuntimeError(
                "compare_reclamm_geometric_noise_runs.py requires JAX to execute "
                "the simulator runs, but JAX is not available in this environment."
            ) from exc
        raise

    from quantammsim.runners.jax_runners import do_run_on_historic_data

    return thermostat_compare, do_run_on_historic_data


def build_default_base_config(thermostat_compare):
    """Return the aggressive AAVE/ETH geometric base config used by the compare script."""
    return dict(thermostat_compare.CONFIGS[1])


def load_adjacent_csv_row(csv_path: Path, row_index: int = 0) -> Mapping[str, object]:
    """Load one row from an adjacent-pairs CSV."""
    frame = pd.read_csv(csv_path)
    if frame.empty:
        raise ValueError(f"Adjacent CSV is empty: {csv_path}")
    if not 0 <= row_index < len(frame):
        raise IndexError(
            f"adjacent-row-index {row_index} is out of range for {len(frame)} rows"
        )
    return frame.iloc[row_index].to_dict()


def build_run_specs_from_adjacent_row(
    row: Mapping[str, object],
    csv_path: Optional[Path] = None,
    row_index: int = 0,
):
    """Convert one adjacent-pairs CSV row into the two run specs this script compares."""
    metric_key = str(row.get("metric_key", "unknown_metric"))
    metric_unit = str(row.get("metric_unit", "value"))
    pair_slug = str(row.get("pair_slug", "unknown_pair"))
    slice_slug = str(row.get("slice_slug", "unknown_slice"))
    adjacency_axis = str(row.get("adjacency_axis", "unknown_axis"))
    diff_abs = float(row["heatmap_value_diff_abs"])
    source_noise_profile = str(row.get("source_noise_profile", "unknown"))

    source_description = (
        f"{pair_slug} {slice_slug} adjacent pair from {metric_key} "
        f"({adjacency_axis}, abs diff={diff_abs:.6f} {metric_unit}, "
        f"noise_profile={source_noise_profile})"
    )
    if csv_path is not None:
        source_description = (
            f"{csv_path.name} row {row_index} | {source_description}"
        )

    run_specs = []
    for prefix, color in (("1", "C0"), ("2", "C1")):
        heatmap_value = float(row[f"{prefix}_heatmap_value"])
        spec = {
            "name": f"Top diff row cell {prefix}",
            "price_ratio": float(row[f"{prefix}_price_ratio"]),
            "centeredness_margin": float(row[f"{prefix}_centeredness_margin"]),
            "daily_price_shift_exponent": float(row[f"{prefix}_daily_price_shift_exponent"]),
            "tvl_usd": float(row[f"{prefix}_tvl_usd"]),
            "color": color,
            "source_noise_profile": source_noise_profile,
            "reason": (
                f"Run derived from adjacent heatmap CSV row {row_index}, cell {prefix}. "
                f"Source={pair_slug}/{slice_slug}, adjacency={adjacency_axis}, "
                f"heatmap_value={heatmap_value:.6f} {metric_unit}, "
                f"noise_profile={source_noise_profile}."
            ),
        }
        run_specs.append(spec)
    return source_description, run_specs


def default_output_file_for_adjacent_csv(csv_path: Path, row_index: int = 0) -> Path:
    """Build a deterministic output PNG path for an adjacent-pairs CSV selection."""
    stem = f"{csv_path.stem}_row_{row_index}_geometric_noise_compare"
    return csv_path.with_name(stem + ".png")


def build_run_config(spec, base_config):
    """Build the base geometric reCLAMM config for one highlighted heatmap cell."""
    cfg = dict(base_config)
    cfg.update(
        {
            "name": spec["name"],
            "price_ratio": float(spec["price_ratio"]),
            "centeredness_margin": float(spec["centeredness_margin"]),
            "daily_price_shift_exponent": float(spec["daily_price_shift_exponent"]),
            "initial_pool_value": float(spec["tvl_usd"]),
            "reason": spec.get(
                "reason",
                "Standalone geometric noise-model comparison run.",
            ),
            "enable_noise_model": True,
        }
    )
    source_noise_profile = spec.get("source_noise_profile")
    if source_noise_profile == "market_linear":
        cfg["noise_model"] = "market_linear"
    elif source_noise_profile not in (None, "", "unknown"):
        raise ValueError(
            "compare_reclamm_geometric_noise_runs.py only supports the current "
            f"market_linear source profile, got {source_noise_profile!r}. "
            "Regenerate the adjacent-pairs CSV with the current heatmap cache."
        )
    return cfg


def build_run_variants(spec, base_config, thermostat_compare):
    """Build matched noise-model and arb-only variants for one highlighted cell."""
    noise_cfg = thermostat_compare.make_noise_variant_cfg(
        build_run_config(spec, base_config=base_config),
        True,
    )
    noise_cfg["variant_key"] = "noise"
    noise_cfg["variant_label"] = "noise-model"

    arb_cfg = thermostat_compare.make_noise_variant_cfg(noise_cfg, False)
    arb_cfg["variant_key"] = "arb"
    arb_cfg["variant_label"] = "arb-only"
    arb_cfg["name"] = noise_cfg["name"]
    arb_cfg["reason"] = (
        f"{noise_cfg['reason']} Matched arb-only baseline with noise disabled."
    )
    return {"spec": spec, "noise": noise_cfg, "arb": arb_cfg}


def build_run_label(cfg, thermostat_compare):
    """Build a compact legend label for a run."""
    return (
        f"{cfg['name']} ({cfg.get('variant_label', 'run')}) | PR {cfg['price_ratio']:.4g}, "
        f"M {cfg['centeredness_margin']:.3g}, "
        f"Shift {cfg['daily_price_shift_exponent']:.3g}, "
        f"TVL {thermostat_compare.format_tvl_millions_label(cfg)}"
    )


def build_time_index(run_fingerprint, periods, step_minutes=1):
    """Return a DatetimeIndex for a result series with the given cadence."""
    return pd.date_range(
        start=pd.Timestamp(run_fingerprint["startDateString"]),
        periods=int(periods),
        freq=f"{max(int(step_minutes), 1)}min",
    )


def infer_series_step_minutes(run_fingerprint, series_length, minute_length):
    """Infer the cadence of a result series from its length."""
    if minute_length and series_length and series_length != minute_length:
        ratio = float(minute_length) / float(series_length)
        rounded_ratio = max(int(round(ratio)), 1)
        if abs(ratio - rounded_ratio) < 1.0e-9:
            return rounded_ratio
    return max(int(run_fingerprint.get("arb_frequency", 1)), 1)


def build_daily_weight_series(
    weights,
    tokens,
    run_fingerprint,
    minute_length,
):
    """Build a daily weight frame from a weight array at inferred cadence."""
    weights = np.asarray(weights, dtype=float)
    weight_step_minutes = infer_series_step_minutes(
        run_fingerprint,
        len(weights),
        minute_length,
    )
    weight_dates = build_time_index(
        run_fingerprint,
        len(weights),
        step_minutes=weight_step_minutes,
    )
    weight_frame = pd.DataFrame(weights, index=weight_dates, columns=tokens)
    return weight_frame.resample("1D").last()


def estimate_gross_volume_usd(cfg, result, default_protocol_fee_split=0.25):
    """Recover gross traded USD volume from LP fee revenue."""
    fee_revenue = result.get("fee_revenue")
    if fee_revenue is None:
        return np.zeros(len(np.asarray(result["value"])), dtype=float)

    fee_revenue = np.asarray(fee_revenue, dtype=float)
    lp_fee_rate_share = float(cfg["fees"]) * (
        1.0 - float(cfg.get("protocol_fee_split", default_protocol_fee_split))
    )
    if lp_fee_rate_share <= 0.0:
        return np.zeros_like(fee_revenue)
    return fee_revenue / lp_fee_rate_share


def build_daily_run_series(cfg, run_fingerprint, result, default_protocol_fee_split=0.25):
    """Build daily TVL/share-price, weight, and volume series for plotting."""
    value = np.asarray(result["value"], dtype=float)
    value_dates = build_time_index(run_fingerprint, len(value), step_minutes=1)
    value_series = pd.Series(value, index=value_dates)
    daily_value = value_series.resample("1D").last()

    zero_fee_weights = np.asarray(result["weights"], dtype=float)
    daily_zero_fee_weights = build_daily_weight_series(
        zero_fee_weights,
        cfg["tokens"],
        run_fingerprint,
        len(value),
    )

    reserves = np.asarray(result["reserves"], dtype=float)
    prices = np.asarray(result["prices"], dtype=float)
    reserve_value = reserves * prices
    reserve_value_totals = np.maximum(
        reserve_value.sum(axis=1, keepdims=True),
        1.0e-12,
    )
    actual_reserve_value_weights = reserve_value / reserve_value_totals
    daily_actual_reserve_value_weights = build_daily_weight_series(
        actual_reserve_value_weights,
        cfg["tokens"],
        run_fingerprint,
        len(value),
    )

    gross_volume_usd = estimate_gross_volume_usd(
        cfg,
        result,
        default_protocol_fee_split=default_protocol_fee_split,
    )
    volume_step_minutes = (
        1
        if len(gross_volume_usd) == len(value)
        else infer_series_step_minutes(run_fingerprint, len(gross_volume_usd), len(value))
    )
    volume_dates = build_time_index(
        run_fingerprint,
        len(gross_volume_usd),
        step_minutes=volume_step_minutes,
    )
    daily_volume = pd.Series(gross_volume_usd, index=volume_dates).resample("1D").sum()

    return {
        "daily_value": daily_value,
        "daily_zero_fee_weights": daily_zero_fee_weights,
        "daily_actual_reserve_value_weights": daily_actual_reserve_value_weights,
        "daily_volume": daily_volume,
    }


def _terminal_json_default(value):
    """Serialize NumPy/JAX-backed values for readable terminal logging."""
    if isinstance(value, Path):
        return str(value)
    if hasattr(value, "tolist"):
        return value.tolist()
    return str(value)


def print_run_inputs_to_terminal(cfg, run_fingerprint, update_params):
    """Print the full run fingerprint and update params for a triggered run."""
    print(
        f"Run inputs for {cfg['name']} ({cfg.get('variant_label', 'run')}):"
    )
    print(
        json.dumps(
            {
                "run_fingerprint": run_fingerprint,
                "update_params": update_params,
            },
            indent=2,
            sort_keys=True,
            default=_terminal_json_default,
        )
    )


def run_single_config(cfg, price_data, thermostat_compare, do_run_on_historic_data):
    """Run one geometric noise-model configuration."""
    run_fingerprint = thermostat_compare.make_fingerprint(cfg, "geometric")
    update_params = thermostat_compare.make_params(cfg)
    print_run_inputs_to_terminal(cfg, run_fingerprint, update_params)
    result = do_run_on_historic_data(
        run_fingerprint=run_fingerprint,
        params=update_params,
        price_data=price_data,
    )
    return {
        "config": cfg,
        "fingerprint": run_fingerprint,
        "noise_summary": thermostat_compare.resolve_reclamm_noise_settings(cfg)[
            "noise_summary"
        ],
        "result": result,
        "series": build_daily_run_series(
            cfg,
            run_fingerprint,
            result,
            default_protocol_fee_split=thermostat_compare.DEFAULT_PROTOCOL_FEE_SPLIT,
        ),
    }


def plot_pair_results(
    run_pairs,
    thermostat_compare,
    source_heatmap_description,
    output_file,
):
    """Plot paired noise-model/arb-only outputs for the two highlighted cells."""
    import matplotlib.pyplot as plt

    fig, axes = plt.subplots(
        5,
        1,
        figsize=(14, 16),
        sharex=True,
        gridspec_kw={"height_ratios": [2.2, 1.5, 1.5, 1.4, 1.6]},
    )
    (
        ax_value,
        ax_zero_fee_weights,
        ax_actual_reserve_weights,
        ax_volume,
        ax_improvement,
    ) = axes

    for pair in run_pairs:
        spec = pair["spec"]
        color = spec["color"]
        noise_output = pair["noise"]
        arb_output = pair["arb"]

        for variant_key, output in (("noise", noise_output), ("arb", arb_output)):
            cfg = output["config"]
            label = build_run_label(cfg, thermostat_compare=thermostat_compare)
            series = output["series"]
            style = VARIANT_STYLES[variant_key]

            ax_value.plot(
                series["daily_value"].index,
                series["daily_value"].to_numpy(dtype=float) / 1e6,
                color=color,
                linestyle=style["linestyle"],
                linewidth=style["linewidth"],
                alpha=style["alpha"],
                label=label,
            )

            for token_idx, token in enumerate(cfg["tokens"]):
                token_linestyle = style["linestyle"] if token_idx == 0 else ":"
                ax_zero_fee_weights.plot(
                    series["daily_zero_fee_weights"].index,
                    series["daily_zero_fee_weights"][token].to_numpy(dtype=float),
                    color=color,
                    linestyle=token_linestyle,
                    linewidth=1.8 if token_idx == 0 else 1.6,
                    alpha=style["alpha"],
                    label=f"{cfg['name']} {cfg['variant_label']} {token}",
                )
                ax_actual_reserve_weights.plot(
                    series["daily_actual_reserve_value_weights"].index,
                    series["daily_actual_reserve_value_weights"][token].to_numpy(
                        dtype=float
                    ),
                    color=color,
                    linestyle=token_linestyle,
                    linewidth=1.8 if token_idx == 0 else 1.6,
                    alpha=style["alpha"],
                    label=f"{cfg['name']} {cfg['variant_label']} {token}",
                )

            ax_volume.plot(
                series["daily_volume"].index,
                series["daily_volume"].to_numpy(dtype=float) / 1e6,
                color=color,
                linestyle=style["linestyle"],
                linewidth=style["linewidth"],
                alpha=style["alpha"],
                label=f"{cfg['name']} {cfg['variant_label']}",
            )

        noise_value, arb_value = noise_output["series"]["daily_value"].align(
            arb_output["series"]["daily_value"],
            join="inner",
        )
        improvement_pct = (noise_value - arb_value) / arb_value * 100.0
        ax_improvement.plot(
            improvement_pct.index,
            improvement_pct.to_numpy(dtype=float),
            color=color,
            linewidth=2.2,
            label=noise_output["config"]["name"],
        )

    shared_noise_summary = run_pairs[0]["noise"]["noise_summary"]
    fig.suptitle(
        "reCLAMM geometric noise-model vs arb-only comparison",
        fontsize=14,
        fontweight="bold",
    )
    fig.text(
        0.5,
        0.965,
        (
            "Compare-script AAVE/ETH fingerprint | "
            f"Cell source: {source_heatmap_description} | "
            f"Noise: {shared_noise_summary} | "
            "Share price equals TVL here because LP supply is fixed at 1.0"
        ),
        ha="center",
        va="top",
        fontsize=10,
    )

    ax_value.set_ylabel("Share price / TVL ($M)")
    ax_value.set_title("Absolute share price / TVL")
    ax_value.grid(True, alpha=0.3)
    ax_value.legend(fontsize=8)

    ax_zero_fee_weights.set_ylabel("Weight")
    ax_zero_fee_weights.set_title("Reported zero-fee empirical weights")
    ax_zero_fee_weights.set_ylim(-0.02, 1.02)
    ax_zero_fee_weights.grid(True, alpha=0.3)
    ax_zero_fee_weights.legend(fontsize=8, ncol=2)

    ax_actual_reserve_weights.set_ylabel("Weight")
    ax_actual_reserve_weights.set_title("Actual reserve value weights")
    ax_actual_reserve_weights.set_ylim(-0.02, 1.02)
    ax_actual_reserve_weights.grid(True, alpha=0.3)
    ax_actual_reserve_weights.legend(fontsize=8, ncol=2)

    ax_volume.set_ylabel("Daily volume ($M)")
    ax_volume.set_title("Estimated gross swap volume")
    ax_volume.grid(True, alpha=0.3)
    ax_volume.legend(fontsize=8)

    ax_improvement.axhline(0.0, color="black", linewidth=0.9, alpha=0.55)
    ax_improvement.set_ylabel("Noise vs arb (%)")
    ax_improvement.set_title("Daily TVL improvement: (noise - arb) / arb")
    ax_improvement.set_xlabel("Date")
    ax_improvement.grid(True, alpha=0.3)
    ax_improvement.legend(fontsize=8)

    output_file = Path(output_file)
    output_file.parent.mkdir(parents=True, exist_ok=True)
    plt.tight_layout(rect=(0.0, 0.0, 1.0, 0.945))
    plt.savefig(output_file, dpi=180)
    print(f"Saved {output_file}")
    plt.close(fig)


def print_final_heatmap_summary(run_pairs, source_heatmap_description):
    """Print the final values and heatmap-equivalent improvement for each pair."""
    print(f"\nSource heatmap selection: {source_heatmap_description}")
    print("Final values represented by the heatmap metric:")
    for pair in run_pairs:
        spec = pair["spec"]
        noise_final = float(pair["noise"]["series"]["daily_value"].iloc[-1])
        arb_final = float(pair["arb"]["series"]["daily_value"].iloc[-1])
        improvement_pct = (noise_final - arb_final) / arb_final * 100.0
        print(
            f"  {spec['name']}: "
            f"noise=${noise_final:,.2f}, "
            f"arb=${arb_final:,.2f}, "
            f"heatmap_improvement={improvement_pct:.6f}%"
        )


def run_pair_comparison(
    run_specs: Sequence[Mapping[str, object]],
    source_heatmap_description: str,
    output_file,
):
    """Run both configs and render the comparison figure."""
    thermostat_compare, do_run_on_historic_data = load_runtime_dependencies()
    base_config = build_default_base_config(thermostat_compare)
    run_pairs = [
        build_run_variants(
            spec,
            base_config=base_config,
            thermostat_compare=thermostat_compare,
        )
        for spec in run_specs
    ]
    run_configs = [
        cfg
        for pair in run_pairs
        for variant_key, cfg in pair.items()
        if variant_key in ("noise", "arb")
    ]
    price_data = thermostat_compare.load_shared_price_data(run_configs)

    completed_pairs = []
    for pair in run_pairs:
        completed_pair = {"spec": pair["spec"]}
        for variant_key in ("noise", "arb"):
            cfg = pair[variant_key]
            print(
                f"Running {cfg['name']} ({cfg['variant_label']}) | "
                f"price_ratio={cfg['price_ratio']}, "
                f"margin={cfg['centeredness_margin']}, "
                f"shift_exp={cfg['daily_price_shift_exponent']}, "
                f"TVL={thermostat_compare.format_tvl_millions_label(cfg)}"
            )
            completed_pair[variant_key] = run_single_config(
                cfg,
                price_data,
                thermostat_compare=thermostat_compare,
                do_run_on_historic_data=do_run_on_historic_data,
            )
        completed_pairs.append(completed_pair)

    plot_pair_results(
        completed_pairs,
        thermostat_compare=thermostat_compare,
        source_heatmap_description=source_heatmap_description,
        output_file=output_file,
    )
    print_final_heatmap_summary(
        completed_pairs,
        source_heatmap_description=source_heatmap_description,
    )
    return output_file


def run_adjacent_csv_row_comparison(
    csv_path,
    row_index: int = 0,
    output_file=None,
):
    """Run the standard geometric comparison using one adjacent-pairs CSV row."""
    csv_path = Path(csv_path)
    row = load_adjacent_csv_row(csv_path, row_index=row_index)
    source_heatmap_description, run_specs = build_run_specs_from_adjacent_row(
        row,
        csv_path=csv_path,
        row_index=row_index,
    )
    resolved_output_file = (
        Path(output_file)
        if output_file is not None
        else default_output_file_for_adjacent_csv(csv_path, row_index=row_index)
    )
    return run_pair_comparison(
        run_specs=run_specs,
        source_heatmap_description=source_heatmap_description,
        output_file=resolved_output_file,
    )


def main(cli_args: Optional[argparse.Namespace] = None):
    """Entry point for CLI execution."""
    args = cli_args or parse_args()
    if args.adjacent_csv:
        return run_adjacent_csv_row_comparison(
            args.adjacent_csv,
            row_index=args.adjacent_row_index,
            output_file=args.output_file,
        )

    output_file = Path(args.output_file) if args.output_file else Path(DEFAULT_OUTPUT_FILE)
    return run_pair_comparison(
        run_specs=DEFAULT_RUN_SPECS,
        source_heatmap_description=DEFAULT_SOURCE_HEATMAP_DESCRIPTION,
        output_file=output_file,
    )


if __name__ == "__main__":
    main()
